*read-in dataset;
data cars;
	set sashelp.cars;
	run;
*get summary of data to reference;
proc contents data=cars;
	run;
*a;
*create frequency table for variables type and drivetrain;
*plot with / plots=freqplot;
proc freq data=cars;
	table type drivetrain / plots=freqplot;
	run;
*b;
*create frequency crosstab for variable drivetrain by type;
*plot with / plots=freqplot;
proc freq data=cars;
	table drivetrain*type /chisq cmh plots=freqplot;
	run;
*c;
*test variable invoice for normality;
proc univariate data=cars normal;
	var invoice;
	run;
*d;
*create a histogram for invoice and compare to the normal distribution;
proc univariate data=cars plot;
	var invoice;
	histogram invoice/normal;
	run;
*e;
*compare mean retail price to mean invoice price;
proc means data=cars n mean std min q1 median q3 max;
	var MSRP invoice;
	output out=pricemeans mean=meanprice;
	run;
*f;
*use proc means on mean and generate summary stats;
proc means data=pricemeans n mean std min q1 median q3 max;
	var MSRP invoice;
	output out=pricemean2;
	run;
*g;
*sort by mpg_city and invoice, in descending order of invoice price;
proc sort data=cars out=sorted;
	by descending invoice MPG_city ;
	run;
*print first 20 obs of sorted data;
proc print data=sorted (obs=20);
	var invoice mpg_city;
	run;
*h;
*find count by "origin" using type and drivetrain;
proc freq data=cars;
	table origin*drivetrain*type; 
	run;
libname path "C:\Users\arobe\OneDrive\Documents\SAS_Data";
*i;
*Create new variable "diff" for MSRP-invoice by region of origin;
data path.cars2; set cars;
	diff = MSRP-invoice;
	keep MSRP invoice origin diff;
	run;
*compare mean difference among origins with proc means;
proc means data=path.cars2 n mean std min q1 median q3 max;
	class origin;
	var diff;
	output out=meanpricediff;
	run;
*j;
*create new set with average invoice by make;
proc means data=cars noprint;
	class make;
	var invoice;
	output out=avgmakeprice mean=average_invoice;
	run;
*print first 10 observations skipping obs 1;
proc print data=avgmakeprice(firstobs=2 obs=11);
	id make;
	var average_invoice;
	run;
