 *Q1. Name data, identify data file location with 'infile';
data bpdata;
	infile "C:\Users\arobe\OneDrive\Documents\SAS_Data\BPDATA.dat";
*read-in non-SAS data using 'input'. label string vars with '$' after.;
	*use @ to identify starting column of var, use number after to identify width, and enclose each var with '.';
	input @1 ID $1. @2 sbp 3. @5 dbp 3. @8 gender $1. @9 age 2. @11 weight 3.;
run;
proc print data=bpdata;
run;
*Q2. Create copy of the dataset and add new variable for weight in kg using arithmetic;
data copyofbpdata;
	set bpdata;
	weight_in_kg = (weight)/2.2046;
run;
*Create a copy of the copy and add new variable that shows the sci notation for weight in kg using format ew;
	*where w=width and we want 2 decimal places;
data copyofbpdata2;
	set copyofbpdata;
	weight_in_kg_scientific_notation = weight_in_kg;
	format weight_in_kg_scientific_notation e9.;
*print new data set;
proc print data=copyofbpdata2;
run;
