*identify path;
libname path "C:\Users\arobe\OneDrive\Documents\SAS_Data";
data Wound; set path.Wound;
run;
*Q1a sort data by sbp;
proc sort data = wound;  
	by sbp;  
	run; 
*Create scatter plot where y=ISS and x=sbp;
proc plot data=Wound;
	plot ISS*sbp;
	title1 'Audrey Robertson 1a';
	run;
*Q1b plot y=ISS, x=sbp by gender;
proc gplot data=Wound;
	plot ISS*sbp=gender;
	title1 'Audrey Robertson 1b';
	run;
*Use goptions to assign colors to each level of gender;
	goptions reset=all;
	goptions hsize=7 vsize=5;
	symbol1 color=hotpink;
	symbol2 color=cornflowerblue;
proc gplot data=Wound;
	plot ISS*sbp=gender;
	title1 'Audrey Robertson 1c';
	run;
*Q1c assign shapes to each level of gender;
	goptions reset=all;
	goptions hsize=7 vsize=5;
	symbol1 value=triangle color=hotpink;
	symbol2 value=square color=cornflowerblue;
proc gplot data=Wound;
	plot ISS*sbp=gender;
	title1 'Audrey Robertson 1d';
	run;
*Q1d assign ascribed line type to each level of gender;
	goptions reset=all;
	goptions hsize=7 vsize=5;
	symbol1 I=JOIN l=1 value='triangle' color=hotpink;
	symbol2 I=JOIN l=2 value='square' color=cornflowerblue;
